#server
server:
  address: localhost
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/quickstart?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
flyway: true
---
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quickstart?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
---
spring:
  profiles:
    active: st
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quickstart?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
---
spring:
  profiles:
    active: uat
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quickstart?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
---
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quickstart?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
flyway: false